
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

readNotification:
  rabbitmq:
    exchange: readNotification.exchange
    topic1ToutingKey: SUBSCRIPTION_PURCHASED
    topic2ToutingKey: SUBSCRIPTION_CANCELED
    topic3ToutingKey: SUBSCRIPTION_RESTARTED

